### ISSUE TITLE
npmjs.com

### ISSUE THREAD

**Issue by Bigismall** [st44100/gulp-styledown#4]
There is a small bug in **Quick Start example** on  https://www.npmjs.com/package/gulp-styledown

Line : pipe(styldown({
should be 

pipe(styl**e**down({

**Comment by Bigismall** [comment]
Done in https://github.com/st44100/gulp-styledown/commit/ec5e8b7501e08180cdae7c43aaf52930ee3b15fc

**Comment by Edgarruiz8585** [comment]
+ > [ruizariasedgarmanuel@gmail.com](`https://github.com/st44100/gulp-styledown/issues/4`)
